apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    name: postgresql
    port: 5432
    targetPort: 5432
  type: ClusterIP
